name: PaulGilbertPhotography
favicon: null
layout_spectrum: 0.94083
typography_spectrum: 0.16329
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfdff'
    - '#000000'
    - '#485a00'
    - '#223100'
    - '#a29c96'
  brandStrength: 0
  lightness: 0.625
  saturation: 0
  rhythmicContrast: 1
purpose: []
